#####################################################################################################
##### MULTISENSOR CAN ESPHOME created by Jarn - https://github.com/jarn78/esphome_multisensor   #####
##### v0.1                                                                                      #####
#####################################################################################################

substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
#  device_name: "multisensor"
  name: ${device_name}
  friendly_name: ${device_name}
  ota_password: ${wifi_password}
  update_interval: 60s
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  project:
    name: "esphome.Multisensor_canopen"
    version: "0.2"
esp32:
  board: esp32dev
  cpu_frequency: 160MHz 
  framework:
    type: arduino
wifi:
  id: wifi_component
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
api:
  encryption:
    key: ${api_encryption_key}
ota:
  - id: ota_std
    platform: esphome
    password: ${ota_password}
logger:
  id: logger_std
  level: DEBUG
switch:
  - platform: restart
    name: "Restart"
i2c:
  - id: sensors
    frequency: 100k
    scl: GPIO22
    sda: GPIO21
sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
output:
  - platform: ledc
    pin: GPIO26
    id: pin_LED
  - platform: gpio
    pin: GPIO27
    id: pin_OUT 
light:
  - platform: monochromatic
    name: "LED"
    id: led
    output: pin_LED
   # internal: True
  - platform: binary
    name: "OUT"
    id: out
    output: pin_OUT
   # internal: True

