#####################################################################################################
##### MULTISENSOR CAN ESPHOME created by Jarn - https://github.com/jarn78/esphome_multisensor   #####
##### v0.1                                                                                      #####
#####################################################################################################


binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO35
      mode:
        input: true
        pullup: true
        
    name: Pin presence
    device_class: presence


