#####################################################################################################
##### MULTISENSOR CAN ESPHOME created by Jarn - https://github.com/jarn78/esphome_multisensor   #####
##### v0.1                                                                                      #####
#####################################################################################################

substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
#  device_name: "multisensor"
  name: ${device_name}
  friendly_name: ${device_name}
  ota_password: ${wifi_password}
  update_interval: 60s
#  node_id: 1

external_components:
  - source: github://mrk-its/esphome-canopen
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  project:
    name: "esphome.Multisensor_canopen"
    version: "0.1"
esp32:
  board: esp32dev
  framework:
    type: arduino
wifi:
  id: wifi_component
  power_save_mode: LIGHT
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
api:
  encryption:
    key: ${api_encryption_key}
ota:
  - id: ota_std
    platform: esphome
    password: ${ota_password}
logger:
  id: logger_std
  level: DEBUG
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
ld2410:
  

switch:
  - platform: ld2410
    bluetooth:
      name: "control bluetooth"
i2c:
  - id: sensors
    frequency: 100k
    scl: GPIO22
    sda: GPIO21
sensor:
  - platform: veml7700
    i2c_id: sensors
    address: 0x10
    update_interval: ${update_interval}
    # short variant of sensor definition:
    ambient_light: 
      name: "Ambient light"
      id: ambient_light
    #  internal: True
    # longer variant of sensor definition:
    actual_gain:
      name: "Actual gain"
      id: gain
    #  internal: True
  - platform: htu21d
    i2c_id: sensors
    model: htu21d
    update_interval: ${update_interval}
    temperature:
      name: "Temperature"
      id: temperature
    #  internal: True
    humidity:
      name: "Humidity"
      id: humidity
    #  internal: True
    heater:
      name: "Heater"
      id: heater
    #  internal: True
  - platform: internal_temperature
    name: "Internal Temperature"
output:
  - platform: ledc
    pin: GPIO26
    id: pin_LED
  - platform: gpio
    pin: GPIO27
    id: pin_OUT 
light:
  - platform: monochromatic
    name: "LED"
    id: led
    output: pin_LED
   # internal: True
  - platform: binary
    name: "OUT"
    id: out
    output: pin_OUT
   # internal: True
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence




