#####################################################################################################
##### MULTISENSOR CAN ESPHOME created by Jarn - https://github.com/jarn78/esphome_multisensor   #####
##### v0.1                                                                                      #####
#####################################################################################################

substitutions:
  ##############################
  ## Change only in your      ##
  ## local yaml substitutions ##
  device_name: multisensor
  name: ${device_name}
  friendly_name: ${device_name}
  ota_password: ${wifi_password}
external_components:
  - source: github://mrk-its/esphome-canopen
esphome:
  name: $(name)
  friendly_name: $(friendly_name)
  min_version: 2024.6.0
  project:
    name: esphome.Multisensor_canopen
    version: 0.1
esp32:
  board: esp32dev
  framework:
    type: arduino
wifi:
  id: wifi_component
  power_save_mode: LIGHT
  networks:
    - id: wifi_default
      ssid: ${wifi_ssid}
      password: ${wifi_password}
ota:
  - id: ota_std
    platform: esphome
    password: ${ota_password}
logger:
  id: logger_std
  baud_rate: 0
i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO33
microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO32
    adc_type: external
    pdm: false
voice_assistant:
  microphone: echo_microphone
  id: va
  on_client_connected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.start_continuous:
          #- script.execute: reset_led
  on_client_disconnected:
    - if:
        condition:
          switch.is_on: use_wake_word
        then:
          - voice_assistant.stop:
          #- light.turn_off: led

